### ISSUE TITLE
History page crashes error AttributeError: module 'resource' has no attribute 'getrusage'

### ISSUE THREAD

**Issue by Soebedar** [SickChill/SickChill#8139]
Branch/Commit: master/b2b09e3720a5e1b4af3d88a165fa8f97d0a44593
OS: Win2022
Browser: Edge
What you did: Clicked on History
What happened: Error AttributeError: module 'resource' has no attribute 'getrusage'
What you expected: open history
Logs:
```
webserver error
Error !
AttributeError: module 'resource' has no attribute 'getrusage'
<div> % if resource: <span class="footer-item">${_('Memory used')}: <span class="footerhighlight">${pretty_file_size(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*1024)}</span></span> | % endif <span class="footer-item">${_('Load time')}: <span class="footerhighlight">${"{:.4f}".format(time() - sbStartTime)}s</span></span> | <span class="footer-item">Mako: <span class="footerhighlight">${"{:.4f}".format(time() - makoStartTime)}s</span></span> | <span class="footer-item">${_('Branch')}: <span class="footerhighlight">${settings.BRANCH}</span></span> | <span class="footer-item">${_('Now')}: <span class="footerhighlight">${datetime.datetime.now().strftime(settings.DATE_PRESET+" "+settings.TIME_PRESET)}</span></span>
C:/Programs/SickChill/sickchill/gui/slick/views/layouts/main.mako, line 381:
<span class="footer-item">${_('Memory used')}: <span class="footerhighlight">${pretty_file_size(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*1024)}</span></span> |
C:\Python310\lib\site-packages\mako\runtime.py, line 940:
callable_(context, *args, **kwargs)


Debug Logs
2022-09-02 11:36:17 INFO :: WEBSERVER-HISTORY_0 :: A mako error occurred: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-09-02 11:34:42 DEBUG :: WEBSERVER-HOME_0 :: git ls-remote --heads origin : returned successful
2022-09-02 11:34:41 DEBUG :: WEBSERVER-HOME_0 :: Executing git ls-remote --heads origin with your shell in C:\Programs\SickChill\sickchill
2022-09-02 11:34:41 DEBUG :: WEBSERVER-HOME_0 :: git symbolic-ref -q HEAD : returned successful
2022-09-02 11:34:41 DEBUG :: WEBSERVER-HOME_0 :: Executing git symbolic-ref -q HEAD with your shell in C:\Programs\SickChill\sickchill
2022-09-02 11:34:41 DEBUG :: WEBSERVER-HOME_0 :: git config remote.origin.url https://github.com/SickChill/SickChill.git : returned successful
```

**Comment by michael-gebis** [comment]
Ran into this myself, was about to submit, so thank you for beating me to the punch.

The problem is the change introduced in 305c06f4a6010567d0bdcdafeb04b73ab783946a , in sickchill/gui/slick/views/layouts/main.mako, line 381, which now reads "if resource:".  Due to the change on line 16, line 381 should now be "if resource is not None:"

This bug will only be visible on Windows, since Python on Windows does not implement the resource package.

**Comment by Soebedar** [comment]
I did some testing after your comment Michael. After i changed line 380 to "if resource is not None:", it still crashes.
Then i removed line 12 to 15 from sickchill/gui/slick/views/layouts/main.mako. Now i access the history page but another error occurs.

```
Traceback (most recent call last):
File C:\Programs\SickChill\sickchill\views\common.py:86, in render:
return self.template.render_unicode(*args, **context)
File C:\Python310\lib\site-packages\mako\template.py:478, in render_unicode:
return runtime._render(
File C:\Python310\lib\site-packages\mako\runtime.py:878, in _render:
_render_context(
File C:\Python310\lib\site-packages\mako\runtime.py:920, in _render_context:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File C:\Python310\lib\site-packages\mako\runtime.py:947, in _exec_template:
callable_(context, *args, **kwargs)
File C:/Programs/SickChill/sickchill/gui/slick/views/layouts/main.mako:328, in render_body:
<%block name="content" />
File C:/Programs/SickChill/sickchill/gui/slick/views/history.mako:82, in render_content:
${"{} - S{:02}E{:02}".format(hItem["show_name"], int(hItem["season"]), int(hItem["episode"]))} ${('', 'Proper')["proper" in hItem["resource"].lower() or "repack" in hItem["resource"].lower()]}
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by pigsyn** [comment]
It seems it only applies to git install on windows using python
pip install works fine on windows

```
Error !
AttributeError: module 'resource' has no attribute 'getrusage'
<div> % if resource: <span class="footer-item">${_('Memory used')}: <span class="footerhighlight">${pretty_file_size(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*1024)}</span></span> | % endif <span class="footer-item">${_('Load time')}: <span class="footerhighlight">${"{:.4f}".format(time() - sbStartTime)}s</span></span> | <span class="footer-item">Mako: <span class="footerhighlight">${"{:.4f}".format(time() - makoStartTime)}s</span></span> | <span class="footer-item">${_('Branch')}: <span class="footerhighlight">${settings.BRANCH}</span></span> | <span class="footer-item">${_('Now')}: <span class="footerhighlight">${datetime.datetime.now().strftime(settings.DATE_PRESET+" "+settings.TIME_PRESET)}</span></span>
D:/GitHub/SickChill/sickchill/gui/slick/views/layouts/main.mako, line 381:
<span class="footer-item">${_('Memory used')}: <span class="footerhighlight">${pretty_file_size(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*1024)}</span></span> |
D:\GitHub\SickChill\.venv\lib\site-packages\mako\runtime.py, line 936:
callable_(context, *args, **kwargs)
```
When opening http://localhost:8081/home it's broken.
![image](https://user-images.githubusercontent.com/3028901/188273040-bc487aab-4dd1-4683-9da7-8c49462f18bc.png)


The try except block doesn't seems to work on windows.

This works (windows and linux containers at least) but there is probably a more elegant solution
https://github.com/SickChill/SickChill/compare/develop...issue_8139

**Comment by ncdaol** [comment]
> It seems it only applies to git install on windows pip install works fine on windows (with SickChillInstaller)

I'm having the same issues with the one installed from the SickChillinstaller.
This is what I see when trying to open home.
![image](https://user-images.githubusercontent.com/37809874/188303207-d96a4a29-080b-4851-ac81-038d40ed5505.png)

**Comment by pigsyn** [comment]
SickChillinstaller works for me (with no other python install)

pip install with python3.10 from python.org works
```
pip3 install -U sickchill
SickChill --datadir=D:\sickchill_win\SickChill\Data
```
Git install on master
```
# git install fails
cd D:\GitHub\SickChill\
python.exe SickChill.py --datadir=D:\sickchill_win\SickChill\Data
# mako error
```
This seems to fix the mako error (given a clean python install)
```
# fixes mako error
cd D:\GitHub\SickChill\
rmdir .venv
python.exe SickChill.py --datadir=D:\sickchill_win\SickChill\Data
# mako error
# ctrl + C
.venv\Scripts\activate
pip3 install poetry_date_version_plugin
deactivate
python.exe SickChill.py --datadir=D:\sickchill_win\SickChill\Data
```

**Comment by miigotu** [comment]
Git install is not recommended. Even if you clone from git, and change to the tests branch, you need to "poetry install"  or "pip install -e . "

Let's just get some guides and docs done so I can release the tests branch.

**Comment by miigotu** [comment]
The poetry_date_version_plugin error goes away if you use poetry 1.1.4 btw, that's an error new to 1.2.0

**Comment by Soebedar** [comment]
I will switch to the windows installer for SickChill, i use Git because of nzbToMedia.

**Comment by lorddain** [comment]
As a quickfix, you can delete lines 381,382,383. This worked for me anyways.

**Comment by miigotu** [comment]
> I will switch to the windows installer for SickChill, i use Git because of nzbToMedia.

The windows installer is hopefully going to change soon to create a proper service that works and to properly link shares between user and administrator/service user.

**Comment by lorddain** [comment]
> ~As a quickfix, you can delete lines 381,382,383. This worked for me anyways.~
> 
> Edit by @miigotu : Do not modify source files or tell people to do that. It causes people to not know how to fix their broken install when it subsequently can no longer update itself.
> 
> A quick fix would be a PR to check `if resource and hasattr(resource, "getrusage"):`

I can understand that, I personally always create backups of any files modified. Just explain to me how auto update would have worked when I can not even access the GUI. Would the code have updated itself in the background regardless? Also how would I have been able to see if the GUI is not accessible.

**Comment by kyuuk** [comment]
@lorddain actually there is an option for autoupdate (not just check updates and show notification), so yes SC would update itself and restart, and probably most users will have that activated

**Comment by lorddain** [comment]
> @lorddain actually there is an option for autoupdate (not just check updates and show notification), so yes SC would update itself and restart, and probably most users will have that activated

Thx, I had that option disabled, its enabled now!

**Comment by Soebedar** [comment]
I switched to windows pip install and SickChill update 2022.9.17 and i have no more crashes of the history page.

i followed [these ](https://github.com/SickChill/SickChill/wiki/Poetry-and-the-history-of-dependencies-in-SickChill)steps to install SickChill with pip.
