### ISSUE TITLE
not snatching anime since update to 2022.8.22

### ISSUE THREAD

**Issue by kyuuk** [SickChill/SickChill#8104]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/ fd5d8f2f7f0973d65a9853aa55f8e99063256a06 
OS: Docker master (latest image tried a pull & also tried git pull inside the image)
![image](https://user-images.githubusercontent.com/16566073/186252267-e1221a89-d28a-41ac-812f-1c44149b5a3c.png)

Logs:
```
2022-08-23 21:35:23 INFO :: SEARCHQUEUE-MANUAL-417658 :: Unable to find a download for: [Vermeil in Gold - S01E08 - TBA]
2022-08-23 21:35:23 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: formatting pattern: %SN - S%0SE%0E - %EN -> Vermeil in Gold - S01E08 - TBA
2022-08-23 21:35:23 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: formatting pattern: %SN - S%0SE%0E - %EN -> Vermeil in Gold - S01E08 - TBA
2022-08-23 21:35:23 INFO :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Performing season pack search for Vermeil in Gold
2022-08-23 21:35:23 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Fallback season pack search initiate
2022-08-23 21:35:23 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Data returned from provider does not contain any torrents
2022-08-23 21:35:23 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: RSS error: module 'drv_libxml2' has no attribute 'create_parser'
2022-08-23 21:35:23 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: GET URL: https://nyaa.si/?page=rss&c=1_0&s=id&o=desc&f=0&q=Kinsou+no+Vermeil+008 [Status: 200]
2022-08-23 21:35:23 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Search String: Kinsou no Vermeil 008
2022-08-23 21:35:23 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Data returned from provider does not contain any torrents
2022-08-23 21:35:23 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: RSS error: module 'drv_libxml2' has no attribute 'create_parser'
2022-08-23 21:35:23 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: GET URL: https://nyaa.si/?page=rss&c=1_0&s=id&o=desc&f=0&q=vermeil+in+gold+08 [Status: 200]
2022-08-23 21:35:22 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Search String: vermeil in gold 08
2022-08-23 21:35:22 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Data returned from provider does not contain any torrents
2022-08-23 21:35:22 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: RSS error: module 'drv_libxml2' has no attribute 'create_parser'
2022-08-23 21:35:22 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: GET URL: https://nyaa.si/?page=rss&c=1_0&s=id&o=desc&f=0&q=Kinsou+no+Vermeil+08 [Status: 200]
2022-08-23 21:35:22 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Search String: Kinsou no Vermeil 08
2022-08-23 21:35:22 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Data returned from provider does not contain any torrents
2022-08-23 21:35:22 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: RSS error: module 'drv_libxml2' has no attribute 'create_parser'
2022-08-23 21:35:22 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: GET URL: https://nyaa.si/?page=rss&c=1_0&s=id&o=desc&f=0&q=Vermeil+in+Gold+08 [Status: 200]
2022-08-23 21:35:21 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Search String: Vermeil in Gold 08
2022-08-23 21:35:21 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Data returned from provider does not contain any torrents
2022-08-23 21:35:21 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: RSS error: module 'drv_libxml2' has no attribute 'create_parser'
2022-08-23 21:35:21 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: GET URL: https://nyaa.si/?page=rss&c=1_0&s=id&o=desc&f=0&q=Kinsou+no+Vermeil%3A+Gakeppuchi+Majutsushi+wa+Saikyou+no+Yakusai+to+Mahou+Sekai+o+Tsukisusumu+08 [Status: 200]
2022-08-23 21:35:21 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Search String: Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai o Tsukisusumu 08
2022-08-23 21:35:21 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Data returned from provider does not contain any torrents
2022-08-23 21:35:21 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: RSS error: module 'drv_libxml2' has no attribute 'create_parser'
2022-08-23 21:35:21 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: GET URL: https://nyaa.si/?page=rss&c=1_0&s=id&o=desc&f=0&q=Vermeil+in+Gold+008 [Status: 200]
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Search String: Vermeil in Gold 008
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Data returned from provider does not contain any torrents
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: RSS error: module 'drv_libxml2' has no attribute 'create_parser'
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: GET URL: https://nyaa.si/?page=rss&c=1_0&s=id&o=desc&f=0&q=vermeil+in+gold+008 [Status: 200]
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Search String: vermeil in gold 008
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Data returned from provider does not contain any torrents
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: RSS error: module 'drv_libxml2' has no attribute 'create_parser'
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: GET URL: https://nyaa.si/?page=rss&c=1_0&s=id&o=desc&f=0&q=Kinsou+no+Vermeil%3A+Gakeppuchi+Majutsushi+wa+Saikyou+no+Yakusai+to+Mahou+Sekai+o+Tsukisusumu+008 [Status: 200]
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Search String: Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai o Tsukisusumu 008
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Search Mode: Episode
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: exceptions_cache: {-1: ['Vermeil in Gold', 'Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai o Tsukisusumu', 'Kinsou no Vermeil', 'vermeil in gold']}
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: get_scene_exceptions: ['vermeil in gold', 'Kinsou no Vermeil', 'Vermeil in Gold', 'Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai o Tsukisusumu']
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: exceptions_cache: {-1: ['Vermeil in Gold', 'Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai o Tsukisusumu', 'Kinsou no Vermeil', 'vermeil in gold']}
2022-08-23 21:35:20 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: get_scene_exceptions: ['vermeil in gold', 'Kinsou no Vermeil', 'Vermeil in Gold', 'Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai o Tsukisusumu']
2022-08-23 21:35:19 INFO :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Performing épisode search for Vermeil in Gold
2022-08-23 21:35:19 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: [Nyaa] :: Last update was too soon, using old cache: 2022-08-23 21:33:15. Updated less then 20 minutes ago
2022-08-23 21:35:19 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: Internal name cache for Vermeil in Gold set to: [ vermeil in gold, kinsou no vermeil gakeppuchi majutsushi wa saikyou no yakusai to mahou sekai o tsukisusumu, kinsou no vermeil ]
2022-08-23 21:35:19 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: exceptions_cache for 417658: {-1: ['Vermeil in Gold', 'Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai o Tsukisusumu', 'Kinsou no Vermeil', 'vermeil in gold']}
2022-08-23 21:35:19 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: get_all_scene_exceptions: {-1: [{'show_name': 'Vermeil in Gold', 'custom': False}, {'show_name': 'Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai o Tsukisusumu', 'custom': False}, {'show_name': 'Kinsou no Vermeil', 'custom': False}, {'show_name': 'vermeil in gold', 'custom': False}]}
2022-08-23 21:35:19 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: Building internal name cache for Vermeil in Gold
2022-08-23 21:35:19 INFO :: SEARCHQUEUE-MANUAL-417658 :: Beginning manual search for: [Vermeil in Gold - S01E08 - TBA]
2022-08-23 21:35:19 DEBUG :: SEARCHQUEUE-MANUAL-417658 :: formatting pattern: %SN - S%0SE%0E - %EN -> Vermeil in Gold - S01E08 - TBA
2022-08-23 21:35:16 DEBUG :: WEBSERVER-HOME_0 :: exceptions_cache: {-1: ['Vermeil in Gold', 'Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai o Tsukisusumu', 'Kinsou no Vermeil', 'vermeil in gold']}
2022-08-23 21:35:16 DEBUG :: WEBSERVER-HOME_0 :: get_scene_exceptions: ['vermeil in gold', 'Kinsou no Vermeil', 'Vermeil in Gold', 'Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai o Tsukisusumu']
```

**Comment by miigotu** [comment]
Something is wrong with your environment.

https://opensource.apple.com/source/libxml2/libxml2-7/libxml2/python/drv_libxml2.py.auto.html

Definitely has create_parser at the end of that file. You can probably |SickChill/.venv/bin/pip install lxml` and avoid this issue.

**Comment by kyuuk** [comment]
Thanks for the help @miigotu, i tried that inside the docker container, and lxml was already installed version `4.9.1`

so i tried a few things, it works with version `4.8.0` and it's broken on `4.9.0` and `4.9.1` of **lxml**


if anyone have the same issue try this:
```
SickChill_dir/.venv/bin/pip uninstall lxml
SickChill_dir/.venv/bin/pip install lxml==4.8.0
```

**Comment by miigotu** [comment]
Hmm, I can pin that I think, but I need to see if there is an upstream fix for that in beautifulsoup4

**Comment by miigotu** [comment]
Yeah that doesn't make any sense. The error above isn't from the c code of lxml, it's from libxml2, and the latest version of that is 2.9.14: 
https://download.gnome.org/sources/libxml2/2.9/
Which has the method you are getting an error about defined. (Open the tar.xz, enter the python folder, open drv_libxm2.py and scroll all the way down.)

Imo somehow your setup just got screwed up, because I can't reproduce this error and I've verified both of those versions of the c library work fine here. lxml isn't even required at all in SC anymore, it runs without it entirely, so it will try to lead it and if it fails it falls back to html.parset silently.

Closing this unless someone else reports the same issue.

**Comment by kyuuk** [comment]
It's weird though because i'm using the docker image, and the issue seems to be only on master image, develop tag works fin

i wont push it further, i'll keep using the develop image for now, 

we'll see if someone else have the same issue

thanks @miigotu

**Comment by miigotu** [comment]
Develop has all of the newest code. Everything gets pushed to develop before it gets to master. There were several bugs fixed in develop related to snatching the other day.

**Comment by kyuuk** [comment]
Hi again @miigotu , it happened with the develop docker image too,


it seems to be linked to SC, the same command work before SC loads and i have the error after it loads with poetry

here is what i tried inside the container

```
root@e8652b0324bd:/app/sickchill# .venv/bin/python3
Python 3.9.13 (main, Aug 23 2022, 09:14:58)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from feedparser import parse
>>> feed = parse("https://nyaa.si/?page=rss&c=1_0&s=id&o=desc&f=0&q=Haikyuu%21%21+12", response_headers={"content-type": "application/xml"})
>>> from sickchill import logger
>>>
>>> feed = parse("https://nyaa.si/?page=rss&c=1_0&s=id&o=desc&f=0&q=Haikyuu%21%21+12", response_headers={"content-type": "application/xml"})
Checking poetry
Can write to /app/sickchill/.venv/lib/python3.9/site-packages: True
Can write to /root/.local/lib/python3.9/site-packages: False
pip installed: True
pip args: /app/sickchill/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed
pip args: /app/sickchill/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU appdirs==1.4.4 babelfish==0.6.0; python_version >= "3.6" and python_version < "4.0" beautifulsoup4==4.11.1; python_full_version >= "3.6.0" beekeeper-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" bencode.py==4.0.0 cachecontrol==0.12.11; python_version >= "3.6" certifi==2022.6.15; python_version >= "3.7" and python_version < "4" cffi==1.15.1; python_version >= "3.6" chardet==5.0.0; python_version >= "3.6" charset-normalizer==2.1.1; python_version >= "3.7" and python_version < "4" and python_full_version >= "3.6.0" cinemagoer==2022.2.11 click==8.1.3; python_version >= "3.7" colorama==0.4.5; python_version >= "3.7" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.7" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==37.0.4; python_version >= "3.6" decorator==5.1.1; python_version >= "3.6" deluge-client==1.9.0 deprecated==1.2.13; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.8; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.10; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==2.0.0a2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") guessit==3.4.3 idna==3.3; python_version >= "3.7" and python_version < "4" ifaddr==0.2.0 imagesize==1.4.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2022.7.9 importlib-metadata==4.12.0; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7") importlib-resources==5.9.0; python_version >= "3.7" and python_version < "3.9" ipaddress==1.0.23 jsonrpclib-pelix==0.4.3.2 kodipydent-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" lxml==4.9.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") mako==1.2.1; python_version >= "3.7" markdown2==2.4.3; python_version >= "3.5" and python_version < "4" markupsafe==2.1.1; python_version >= "3.7" msgpack==1.0.4; python_version >= "3.6" new-rtorrent-python==1.0.1a0 oauthlib==3.2.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==21.3; python_version >= "3.6" pbr==5.10.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pycparser==2.21; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjwt==2.4.0; python_version >= "3.6" pynacl==1.5.0; python_version >= "3.6" pynma==1.0 pyopenssl==22.0.0; python_version >= "3.6" pyparsing==3.0.9; python_full_version >= "3.6.8" and python_version >= "3.6" pysrt==1.1.2 python-dateutil==2.8.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==6.1.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") python-twitter==3.5 python3-fanart==2.0.0 pytz==2022.2.1 qbittorrent-api==2022.8.37 rarfile==4.0 rebulk==3.1.0 requests-oauthlib==1.3.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests==2.28.1; python_version >= "3.7" and python_version < "4" sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" soupsieve==2.3.2.post1; python_version >= "3.6" and python_full_version >= "3.6.0" sqlalchemy==1.4.40; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.5.0; python_version >= "3.6" subliminal==2.1.0 text-unidecode==1.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" timeago==1.0.16 tmdbsimple==2.9.1 tornado==6.2; python_version >= "3.7" tus.py==1.3.4 tvdbsimple==1.0.6 typing-extensions==4.3.0; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7") unidecode==1.3.4; python_version >= "3.5" urllib3==1.26.12; python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "4" or python_full_version >= "3.6.0" and python_version < "4" and python_version >= "3.7" validators==0.20.0; python_version >= "3.4" win-inet-pton==1.1.0 wrapt==1.14.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" xmltodict==0.13.0; python_full_version >= "3.6.2" and python_version < "4" and python_version >= "3.4" zipp==3.8.1; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7")
Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.15 requires packaging<21.0,>=20.4, but you have packaging 21.3 which is incompatible.

>>> feed = parse("https://nyaa.si/?page=rss&c=1_0&s=id&o=desc&f=0&q=Haikyuu%21%21+12", response_headers={"content-type": "application/xml"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/sickchill/.venv/lib/python3.9/site-packages/feedparser/api.py", line 251, in parse
    saxparser = xml.sax.make_parser(PREFERRED_XML_PARSERS)
  File "/usr/local/lib/python3.9/xml/sax/__init__.py", line 80, in make_parser
    return _create_parser(parser_name)
  File "/usr/local/lib/python3.9/xml/sax/__init__.py", line 105, in _create_parser
    return drv_module.create_parser()
AttributeError: module 'drv_libxml2' has no attribute 'create_parser'
```

maybe linked to this 
`Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.15 requires packaging<21.0,>=20.4, but you have packaging 21.3 which is incompatible.`

but i don't know what to do more to help, sorry

**Comment by kyuuk** [comment]
i was able to debug the code, and found something weird : 
the module is imported with `DependencyInjectorLoader` from SC `init_helpers.py`
but `DependencyInjectorLoader.create_module` returns None, we go into the ModuleNotFoundError except, with poetry_ran True so it doesn't do anything 
![image](https://user-images.githubusercontent.com/16566073/187073910-80bc31e3-5e60-4dc7-84f7-81c686636f4c.png)

![image](https://user-images.githubusercontent.com/16566073/187073673-28159686-3306-4156-bdc4-d0d1d105d17d.png)
but on the next step in the exec_module function there is a module object 
![image](https://user-images.githubusercontent.com/16566073/187073691-5c11a6bc-b08b-4ff9-a73f-936130d07ec9.png)
but with nothing in it 
![image](https://user-images.githubusercontent.com/16566073/187073721-8e8dbaa7-7244-4339-b459-2cf177d86f81.png)

any clue on where the problem could be ?
some help would be appreciated 😄

**Comment by miigotu** [comment]
I should have went and put some sort of functools.wraps around that class so you could see the actual caller and information. I'm catching import errors there and running poetry_install one time per application run. If poetry installs and the import errors remains, it isn't because we don't have something installed, it's because the import is erroring for example because a symbol that's being asked for is missing. 

I want to do away with the poetry install code entirely, because the proper way is to never install dependencies or updates to a python application from its own code. I rather the updater handle calling an external script or package to do it, or the updater itself being an entirely different release (that would be an installer and an updater) that would sort of watch for updates to SC and install the new updates. systemctl start sickchill-updater or something like that lol.

It's a mess right now, and finicky. I think I'd rather the code just fail to start, and people need to fix the install. Or maybe, it should try to restart and fix the install once rather than do it during runtime.

Once the wiki and guides are updated we can figure out what to do there, but I'm not looking forward to a truck load of new issues when people's SC fails to start the next time we update a dependency so removing it's going to have to wait for a bit.

About feedparser though, I think we can remove that entirely now and use bs4_parser, since feedparser is not so reliable.

**Comment by kyuuk** [comment]
Okay, so nothing to do at the moment,
thanks for the reply @miigotu 😄 

i'll try to keep testing the develop image
