### ISSUE TITLE
Sickchill UI unavailable after upgrade to 2022.8.22- attempted uninstall/reinstall did not fix

### ISSUE THREAD

**Issue by davidreverett** [SickChill/SickChill#8106]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed) Unable to access the UI to do this. 

Branch/Commit: Master 2022.8.22
OS: Windows 10
Browser: Chrome 104.0.5112.102
What you did: Received Update alert in UI- clicked to Update
What happened: Error displayed on screen: A mako error occurred: module 'sickchill.settings' has no attribute 'NO_LGMARGIN'
What you expected:Update to complete successfully. Tried to uninstall/reinstall- UI is not responsive- Chrome displays error Site could not be loaded- ERR_CONNECTION_TIMED_OUT
Logs:
```
2022-08-24 10:18:34 INFO :: EVENT-QUEUE :: Aborting all threads
2022-08-24 10:18:34 INFO :: EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2022-08-24 10:18:34 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: module 'sickchill.settings' has no attribute 'NO_LGMARGIN'
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the SHOWQUEUE-ADD thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the SEARCHQUEUE-BACKLOG-363955 thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR-AUTO thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the NOTIFICATIONS thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Saving all shows to the database
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Saving config file to disk
2022-08-24 10:18:35 INFO :: EVENT-QUEUE :: Shutting down Tornado
2022-08-24 10:18:45 INFO :: EVENT-QUEUE :: Restarting SickChill with ['C:\\SickChill\\Python3\\tools\\python.exe', 'C:\\SickChill\\Python3\\tools\\lib\\site-packages\\SickChill.py', '--nolaunch', '--port=8081', '--datadir=C:\\SickChill\\Data']

```

**Comment by DrDrewZA** [comment]
Had a similar prblem - read and do this:
#8101

**Comment by davidreverett** [comment]
@DrDrewZA You are awesome- that fixed the problem :)
