### ISSUE TITLE
scheduler "alive" statuses all red

### ISSUE THREAD

**Issue by OneCDOnly** [SickChill/SickChill#6637]
Reported by @GTunney a few hours ago on the [QNAP forum](https://forum.qnap.com/viewtopic.php?p=761829#p761829). This is a very recent clone from the `develop` branch :

![screenshot](https://i.imgur.com/wuTIfmX.png)

How do we get these to go green again?

Thank you.

**Comment by miigotu** [comment]
Cannot reproduce this:
![image](https://user-images.githubusercontent.com/390379/90189369-0c9c8b80-dd8b-11ea-91ce-a719e6ac857f.png)

**Comment by miigotu** [comment]
Is that on python 3.8??

**Comment by OneCDOnly** [comment]
I'm not sure about @GTunney's version, but as it's installed via sherpa, it will be either Python 3.8.3 or Python 3.7.4

My Debian 10.5 installation running the same SickChill with Python 3.7.3 is also showing all red. :disappointed:

**Comment by miigotu** [comment]
Update from the develop branch and see if #6638 fixes it.

**Comment by OneCDOnly** [comment]
Nope, no change: Still all red. Not sure if this is relevant, but these services still seem to be running fine. The `last run` times for each are updated when they should be. :confused: 

Also, the `daily search` and `backlog search` times are both shown as `0:00:00`

![screenshot](https://i.imgur.com/9Ofxskk.png)

**Comment by OneCDOnly** [comment]
update: just did a quick check by reverting back to a `master` branch install. All green `alive` statuses. `daily search` and `backlog search` times appear normal.

**Comment by OneCDOnly** [comment]
@miigotu what does the `alive` status actually mean? Might help track-down the issue.

**Comment by miigotu** [comment]
It's built into python, it's the function to check if a thread is running.

It doesn't make sense that it's not showing correctly if the threads are actually running.

**Comment by OneCDOnly** [comment]
OK, let me know if there's anything I can check that'll help.

**Comment by GTunney** [comment]
Sorry chaps only just morning here. 

Yes I’m running python 3.7.4 via Sherpa.sh

**Comment by OneCDOnly** [comment]
Good work @miigotu - a fresh clone finally shows some green. :grin:

![screenshot](https://i.imgur.com/2pDJs0I.png)

**Comment by miigotu** [comment]
I'm gonna make a test app to see if it shows you dead threads in that. I'm feeling like y'all have a python that is patched by your distro or custom compiled with the incorrect options and that's causing the big, because the code is good on this side.

I will post it later.

**Comment by OneCDOnly** [comment]
> I'm gonna make a test app to see if it shows you dead threads in that. I'm feeling like y'all have a python that is patched by your distro or custom compiled with the incorrect options and that's causing the big, because the code is good on this side.
> 
> I will post it later.

Oh, then you're not going to like this. :wink:

I get the same problem on 2 different Linux platforms:

- Debian 10.5 with Python 3.7.3
- QTS 4.2.6 with Python 3.8.3 from OpenWRT

If I was to guess a common element between these two (other than I installed SickChill on both), it's that way-back-when, QTS was originally derived from Ubuntu (so, Debian after Canonical have fcsk'd with it). But the Pythons come from different sources.

As this worked on Python 2.7.5, maybe there's some extra module needed for SickChill to work in Python 3? (I know - not a lot of help, but my own Python experience is quite limited).

**Comment by miigotu** [comment]
It works fine here on Ubuntu Eoan in 3.7 and 3.8

**Comment by OneCDOnly** [comment]
Well, this is embarrassing. I tried a new install on my workstation - and installed everything in `requirements.txt` (which I hadn't been doing). Works fine. 👍🏽 

My bad. 😞 

@miigotu I'll address this now, and my sincere apologies for stuffing you around.

**Comment by OneCDOnly** [comment]
BTW: this is what I get now after having ensured everything in `requirements.txt` is installed:
![screenshot](https://i.imgur.com/3v19271.png)

**Comment by miigotu** [comment]
what wasnt installed? because it is all supposed to be in lib3 also

**Comment by OneCDOnly** [comment]
I hadn't specifically installed everything shown in the develop branch `requirements.txt` file. I was still working off my old list of pips that worked with the Python 2 version of SickChill. 

After installing with `pip3 install -r requirements.txt`, the alive column worked as expected. 😄

**Comment by miigotu** [comment]
lol

**Comment by OneCDOnly** [comment]
hmmm... looks like I'm not out of the woods yet. That fix didn't work on my production server (Debian 10.5), and it's now giving me a mako error on the show list page. I've just finished reinstalling Python 3 from scratch (no small feat), and it's still there. 😞 

May I ask: any idea if this error is something wrong with my config or database?
```
File /opt/SickChill/sickchill/gui/slick/views/inc_home_show_list.mako:206, in render_body:
data-src="${static_url(curShow.networknetwork_image_url)}"
AttributeError: 'TVShow' object has no attribute 'networknetwork_image_url'
```            
Looks like a typo.

**Comment by miigotu** [comment]
Sure looks like a typo to me.

**Comment by miigotu** [comment]
Fixed
