### ISSUE TITLE
'trimHistory()` error preventing GUI from loading

### ISSUE THREAD

**Issue by albeec13** [SickChill/SickChill#8040]
After updating to latest Sickchill via Arch linux AUR package, the GUI is no longer loading, instead leaving a white page, while the underlying service seems to be running correctly.

I was able to use the logs to isolate the error location and commenting out the following lines near line 200 allowed the page to load properly:
```
        # sure, why not?
        #if settings.USE_FAILED_DOWNLOADS:
        #    failed_history.trimHistory()
```
Seems to be working ok after that change, but looks like there might be an issue with `trimHistory()`

Branch/Commit: v2022.07.20
OS: Arch Linux
Browser: Firefox
What you did: Attempted to open GUI
What happened: White blank page and error logs
What you expected: Sickchill GUI
Logs:
```
Jul 26 11:18:38 arch systemd[1]: Stopping SickChill Daemon...
Jul 26 11:18:39 arch systemd[1]: Stopped SickChill Daemon.
Jul 26 11:18:39 arch systemd[1]: Started SickChill Daemon.
Jul 26 11:18:40 arch SickChill.py[967919]: Checking poetry
Jul 26 11:18:40 arch SickChill.py[967919]: sickchill installed: True
Jul 26 11:18:48 arch SickChill.py[967919]: sickchill installed: True
Jul 26 11:18:48 arch SickChill.py[967919]: /opt/sickchill/app/bin/SickChill.py:103: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
Jul 26 11:18:48 arch SickChill.py[967919]:   threading.currentThread().name = "MAIN"
Jul 26 11:18:49 arch SickChill.py[967919]: sickchill installed: True
Jul 26 11:18:49 arch SickChill.py[967919]: Traceback (most recent call last):
Jul 26 11:18:49 arch SickChill.py[967919]:   File "/opt/sickchill/app/bin/SickChill.py", line 357, in <module>
Jul 26 11:18:49 arch SickChill.py[967919]:     SickChill().start()
Jul 26 11:18:49 arch SickChill.py[967919]:   File "/opt/sickchill/app/bin/SickChill.py", line 201, in start
Jul 26 11:18:49 arch SickChill.py[967919]:     failed_history.trimHistory()
Jul 26 11:18:49 arch SickChill.py[967919]: AttributeError: module 'sickchill.oldbeard.failed_history' has no attribute 'trimHistory'
```

**Comment by miigotu** [comment]
Your sickchill.py is not up to date, and neither are your templates. failed_history was removed entirely in a1c9d30010a80efb63505adbd9a829715d327e13 on 3/9/22 and combined with the history class

**Comment by albeec13** [comment]
Thanks @miigotu , I notified the package maintainer first, but since it seemed the package was up-to-date, it may be an issue with upgrades not being handled correctly. I will follow up with that side. Thanks again!

**Comment by miigotu** [comment]
Likely because many projects the "script" file is just a pointer to the actual entry to the program, when ours changes yours isn't updated as it is assumed to not change.

**Comment by albeec13** [comment]
Just an FYI, after uninstalling, "git clean"-ing, resyncing, and rebuilding/reinstalling, my systemd  service was failing to launch, which turned out to be because /opt/sickchill/app/bin/Sickchill no longer has a .py extension. After modifying the service to point to the non-.py version, it looks like everything launched fine with the latest code. I think there might be some upgrading issues with that package, but going forward, it might be good to uninstall/reinstall each time.
